Repository Indus-Action-Initiatives/rte-mis, pull requests merged in 2024-09, with the labels that each got.

#447 RTEMIS-256: Modified the logs panel.
  modules/rte_mis_logs/js/logging.js
  modules/rte_mis_logs/js/scroll-to-top.js
  modules/rte_mis_logs/rte_mis_logs.libraries.yml
Labels: Sprint 11

#446 RTEMIS-0: Added the condition check for academic session check.
  modules/rte_mis_core/rte_mis_core.inc
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
Labels: Sprint 11

#448 RTEMIS-264: View panel for filelog entries theming.
  modules/rte_mis_gin/js/script.js
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 11

#440 RTEMIS-202: Added auto promotion cron for student tracking.
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.block_admin.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.school.yml
  config/install/user.role.school_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.default.yml
  modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.student_tracking_modify.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.allocation_details.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.default.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.pdf.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_student_tracking_status.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_student_tracking_status.yml
  modules/rte_mis_student_tracking/config/install/workflow.state.student_tracking_workflow_creation.yml
  modules/rte_mis_student_tracking/config/install/workflow.state.student_tracking_workflow_dropout.yml
  modules/rte_mis_student_tracking/config/install/workflow.state.student_tracking_workflow_edu_completed.yml
  modules/rte_mis_student_tracking/config/install/workflow.state.student_tracking_workflow_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_creation_dropout.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_creation_edu_completed.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_creation_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_dropout_dropout.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_dropout_edu_completed.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_dropout_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_edu_completed_dropout.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_edu_completed_edu_completed.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_edu_completed_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_studying_dropout.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_studying_edu_completed.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_studying_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.workflow.student_tracking_workflow.yml
  modules/rte_mis_student_tracking/drush.services.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.install
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
  modules/rte_mis_student_tracking/src/Access/PerformanceDetailEditAccessCheck.php
  modules/rte_mis_student_tracking/src/Commands/StudentTrackingCommandsForTesting.php
  modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
  rte_mis.install
  scripts/student_tracking/process_student_tracking_queue.sh
Labels: Sprint 11

#451 RTEMIS-229: Student tracking dashboard theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 11

#454 RTEMIS-229: Student tracking dashboard theming for tab.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 11

#461 RTEMIS-256: Updated the PR with the created column and removed filter fields.
  modules/rte_mis_logs/config/install/rte_mis_logs.settings.yml
  modules/rte_mis_logs/js/logging.js
  modules/rte_mis_logs/rte_mis_logs.install
Labels: Update Hook

#462 RTEMIS-264: View panel logs theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 11

#464 RTEMIS-269: Added the module for the reimbursement and created one field for academic year.
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.state_fees_details.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.state_fees_details.default.yml
  modules/rte_mis_reimbursement/config/install/eck.eck_type.mini_node.state_fees_details.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.state_fees_details.field_academic_year.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml
  rte_mis.info.yml
  rte_mis.install
Labels: Update Hook

#468 RTEMIS-269: Added the paragraph state fees and it's three fields.
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.state_fees_details.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.state_fees_details.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.paragraph.state_fees.default.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.state_fees_details.field_state_fees.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_board_type.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_amount.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_type.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_state_fees.yml
  modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_amount.yml
  modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_type.yml
  modules/rte_mis_reimbursement/config/install/paragraphs.paragraphs_type.state_fees.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Labels: Sprint 12

#458 RTEMIS-265: Modified the dashboard for school admin.
  config/install/views.view.allotted_student.yml
  config/install/views.view.mapped_habitation.yml
  modules/rte_mis_core/config/install/dashboards.dashboard.school_dashboard.yml
  modules/rte_mis_core/rte_mis_core.install
  modules/rte_mis_logs/src/Logger/CustomFileLog.php
  modules/rte_mis_school/src/Plugin/Block/SchoolAllottedStudentsBlock.php
  modules/rte_mis_school/src/Plugin/Block/SchoolHabitationBlock.php
  modules/rte_mis_school/src/Plugin/Block/StudentTrackingBlock.php
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
  rte_mis.install
Labels: Update Hook

#463 RTEMIS-275: Added the unallotted student for the next lottery condition.
  config/install/views.view.lottery_results.yml
  modules/rte_mis_lottery/asset/format.json
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Form/SendSmsConfirmForm.php
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  rte_mis.install
Labels: Update Hook

#466 RTEMIS-261: Updated student application field to also show allocation status.
  modules/rte_mis_allocation/rte_mis_allocation.module
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  modules/rte_mis_student/config/install/views.view.student_applications.yml
  modules/rte_mis_student/rte_mis_student.install
  modules/rte_mis_student/rte_mis_student.views.inc
  modules/rte_mis_student/src/Plugin/views/field/StudentApplicationStatusField.php
Labels: Update Hook

#471 RTEMIS-268: Added rte mis reimbursment configuration form.
  config/install/user.role.state_admin.yml
  modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml
  modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.links.menu.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.permissions.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.routing.yml
  modules/rte_mis_reimbursement/src/Form/RteMisReimbursementConfigForm.php
  rte_mis.install
Labels: Sprint 12

#476 RTEMIS-269: Added checkboxes for fee type.
  modules/rte_mis_core/rte_mis_core.inc
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_amount.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_fees_type.yml
  modules/rte_mis_reimbursement/config/install/field.storage.paragraph.field_fees_type.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  rte_mis.install
Labels: Sprint 12

#479 RTEMIS-268: Modified the update hook.
  rte_mis.install
Labels: Sprint 12

#481 RTEMIS-268: Added reimbursement config form link for state admin.
  config/content/menu_link_content/content-bulk-export-18_06_2024-16_35.zip
  config/install/menu_export.export_data.yml
Labels: Sprint 12

#477 RTEMIS-277: Added condition for education details check.
  modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_education_details.yml
  modules/rte_mis_school/rte_mis_school.install
  modules/rte_mis_school/rte_mis_school.module
  rte_mis.install
Labels: Update Hook, Sprint 12

#483 RTEMIS-277: Added condition for category on education details.
  modules/rte_mis_school/rte_mis_school.module
Labels: Sprint 12

#486 RTEMIS-270: Added the code to reimbursement service.
  modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php
  modules/rte_mis_core/rte_mis_core.inc
  modules/rte_mis_core/src/Plugin/Menu/AlterTaxonomyActionTask.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php
  modules/rte_mis_student/src/CustomVocabularyListBuilder.php
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
  modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
Labels: Sprint 12

#487 RTEMIS-270: Modified the school claim entity.
  config/install/user.role.school_admin.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.allocation_details.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_academic_session_tracking.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_payment_head.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_approval_authority.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Labels: Sprint 13

#489 RTEMIS-286: Reimbursement student tracking node theming.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Labels: Sprint 13

#491 RTEMIS-284: Added board type to pdf format.
  modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml
  modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.pdf.yml
  modules/rte_mis_school/rte_mis_school.install
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 13

#490 RTEMIS-279: Added a panel for school admin to see all his claim requests.
  config/content/menu_link_content/content-bulk-export-18_06_2024-16_35.zip
  config/install/menu_export.export_data.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.links.action.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#494 RTEMIS-284: Removed the title for board type.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 13

#492 RTEMIS-278: Updated block and district admin dashboard.
  config/content/menu_link_content/content-bulk-export-18_06_2024-16_35.zip
  config/install/menu_export.export_data.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.allocation_details.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_amount_received.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_total_fees.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_amount_received.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_total_fees.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#496 RTEMIS-270: Changed class attribute to id.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Labels: Sprint 13

#499 RTEMIS-278: Updated reimbursement dashboard for district, block and state admins.
  config/install/pathauto.pattern.school_claim_alias.yml
  config/install/user.role.block_admin.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.school_claim_modify.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_mode.mini_node.school_claim_modify.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_amount_received.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_payment_head.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/rte_mis_reimbursement.views.inc
  modules/rte_mis_reimbursement/src/Plugin/views/field/ReimbursementBalanceAmountField.php
Labels: Sprint 13

#498 RTEMIS-283: Configured the sms and mail services on claim status change.
  modules/rte_mis_mail/src/Form/RteMisMailConfigForm.php
  modules/rte_mis_reimbursement/rte_mis_reimbursement.info.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
Labels: Sprint 13
