Repository Indus-Action-Initiatives/rte-mis, pull requests merged in 2024-10, with the labels that each got.

#502 RTEMIS-270: Modified claim entity validation.
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#500 RTEMIS-280: Added new states for payment status in reimbursement workflow.
  config/install/user.role.state_admin.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.school_claim_modify.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml
  modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.state.reimbursement_claim_workflow_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_beo_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_beo_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_deo_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_approved_by_deo_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_creation_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_creation_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_approved_by_beo.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_approved_by_deo.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_rejected.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_completed_submitted.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_approved_by_beo.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_approved_by_deo.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_rejected.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_payment_pending_submitted.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_rejected_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_rejected_payment_pending.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_submitted_payment_completed.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_submitted_payment_pending.yml
  modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Form/RteMisReimbursementConfigForm.php
  modules/rte_mis_reimbursement/src/Plugin/views/field/ReimbursementBalanceAmountField.php
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
  rte_mis.install
Labels: Sprint 13

#501 RTEMIS-290: Modified the school fee detail entity & claim entity.
  config/install/user.role.state_admin.yml
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_core/rte_mis_core.inc
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_form_display.paragraph.state_fees.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.allocation_details.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.default.yml
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.paragraph.state_fees.default.yml
  modules/rte_mis_reimbursement/config/install/field.field.mini_node.school_claim.field_academic_session_claim.yml
  modules/rte_mis_reimbursement/config/install/field.field.paragraph.state_fees.field_education_level.yml
  modules/rte_mis_reimbursement/config/install/field.storage.mini_node.field_academic_session_claim.yml
  modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml
  modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml
  modules/rte_mis_reimbursement/src/Access/SchoolClaimEditAccessCheck.php
  modules/rte_mis_reimbursement/src/Access/SchoolClaimViewAccessCheck.php
  modules/rte_mis_reimbursement/src/Form/RteMisReimbursementConfigForm.php
  modules/rte_mis_reimbursement/src/Routing/RouteSubscriber.php
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#506 RTEMIS-280: Added access checks for update operation for reimbursement status.
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#511 RTEMIS-289: Added student tracking dashboard for block admin.
  config/install/user.role.block_admin.yml
  config/install/views.view.student_tracking_dashboard.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.allocation_details.yml
  modules/rte_mis_student_tracking/config/install/workflow.transition.student_tracking_workflow_dropout_studying.yml
  modules/rte_mis_student_tracking/config/install/workflow.workflow.student_tracking_workflow.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.install
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
  rte_mis.install
Labels: Update Hook, Sprint 13

#510 RTEMIS-287: Added the feature for the block to edit school fee.
  config/install/form_mode_control.settings.yml
  config/install/user.role.block_admin.yml
  config/install/views.view.academic_sessions_list.yml
  modules/rte_mis_core/src/EventSubscriber/RouteRedirectSubscriber.php
  modules/rte_mis_reimbursement/rte_mis_reimbursement.links.action.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_fee_modify.yml
  modules/rte_mis_school/config/install/core.entity_form_mode.mini_node.school_fee_modify.yml
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_school/rte_mis_school.services.yml
  modules/rte_mis_school/src/Access/SchoolDetailEditAccessCheck.php
Labels: Sprint 13

#512 RTEMIS-280: Fixed the regression issue.
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 13

#514 RTEMIS-289: Updated student tracking promotion for education complete scenario and code optimization.
  modules/rte_mis_core/rte_mis_core.inc
  modules/rte_mis_student_tracking/src/Plugin/QueueWorker/StudentTrackingQueue.php
Labels: Sprint 13

#515 RTEMIS-282: Modified the field view values for claim entity.
  modules/rte_mis_reimbursement/config/install/core.entity_view_display.mini_node.school_claim.pdf.yml
Labels: Sprint 13

#517 RTEMIS-282: Modified the code.
  config/install/views.view.student_tracking_dashboard.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
  modules/rte_mis_reimbursement/templates/eck-entity--mini-node--school-claim--pdf.html.twig
Labels: Sprint 13

#521 RTEMIS-290: Modified the permission for block admin.
  config/install/user.role.block_admin.yml
Labels: Sprint 13

#523 RTEMIS-280: Reset reimbursement claim when state or school fees details are updated.
  config/install/views.view.reimbursement_claim.yml
  modules/rte_mis_reimbursement/config/install/rte_mis_reimbursement.settings.yml
  modules/rte_mis_reimbursement/config/install/workflow.transition.reimbursement_claim_workflow_reset_submitted.yml
  modules/rte_mis_reimbursement/config/install/workflow.workflow.reimbursement_claim_workflow.yml
  modules/rte_mis_reimbursement/config/schema/rte_mis_reimbursement.schema.yml
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/rte_mis_reimbursement.services.yml
  modules/rte_mis_reimbursement/src/Access/SchoolClaimEditAccessCheck.php
  modules/rte_mis_reimbursement/src/Plugin/QueueWorker/ResetReimbursementClaimQueue.php
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
  scripts/reimbursement/process_reimbursement_claim_queue.sh
Labels: Sprint 14

#524 RTEMIS-280: Fixed school fees details update issue.
  modules/rte_mis_reimbursement/rte_mis_reimbursement.module
  modules/rte_mis_reimbursement/src/Services/RteReimbursementHelper.php
Labels: Sprint 14

#530 RTEMIS-295: Created a report section for school registration reports.
  modules/rte_mis_gin/scss/base/_reset.scss
  modules/rte_mis_report/rte_mis_report.info.yml
  modules/rte_mis_report/rte_mis_report.routing.yml
  modules/rte_mis_report/rte_mis_report.services.yml
  modules/rte_mis_report/src/Controller/SchoolRegistrationReportBlockController.php
  modules/rte_mis_report/src/Controller/SchoolRegistrationReportController.php
  modules/rte_mis_report/src/Services/RteReportHelper.php
  rte_mis.info.yml
Labels: Sprint 14

#529 RTEMIS-297: Access denied page theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 14

#533 RTEMIS-294: Added a report dashboard for school habitation mapping.
  modules/rte_mis_report/rte_mis_report.routing.yml
  modules/rte_mis_report/src/Controller/HabitationMappingReportDashboard.php
  modules/rte_mis_report/src/Form/HabitationReportForm.php
  modules/rte_mis_report/src/Services/RteReportHelper.php
Labels: Sprint 14

#534 RTEMIS-296: Added education level and board type filters for school registration report.
  modules/rte_mis_report/src/Controller/SchoolInformationReportSchoolList.php
  modules/rte_mis_report/src/Controller/SchoolRegistrationReportBlockController.php
  modules/rte_mis_report/src/Form/SchoolRegistrationReportFilterForm.php
  modules/rte_mis_report/src/Services/RteReportHelper.php
Labels: Sprint 14

#535 RTEMIS-294: Modified the logic for empty values.
  modules/rte_mis_report/src/Controller/HabitationMappingReportDashboard.php
Labels: Sprint 14
