Repository Indus-Action-Initiatives/rte-mis, pull requests merged in 2024-07, with the labels that each got.

#330 RTEMIS-182: Student mapping with School & Lottery Status Table.
  modules/rte_mis_lottery/config/install/rte_mis_lottery.settings.yml
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/rte_mis_lottery.links.menu.yml
  modules/rte_mis_lottery/rte_mis_lottery.module
  modules/rte_mis_lottery/rte_mis_lottery.routing.yml
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Form/LotteryConfigForm.php
  modules/rte_mis_lottery/src/Services/ClearTableManager.php
  modules/rte_mis_student/config/optional/core.entity_form_display.mini_node.school_details.default.yml
  modules/rte_mis_student/config/optional/core.entity_form_display.mini_node.school_details.school_detail_edit.yml
  modules/rte_mis_student/config/optional/core.entity_view_display.mini_node.school_details.default.yml
  modules/rte_mis_student/config/optional/core.entity_view_display.mini_node.school_details.pdf.yml
  modules/rte_mis_student/config/optional/field.field.mini_node.school_details.field_allotted_students.yml
  modules/rte_mis_student/config/optional/field.storage.mini_node.field_allotted_students.yml
Labels: Sprint 8

#342 RTEMIS-179: Added school details in lottery form.
  config/install/user.role.state_admin.yml
  modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php
  modules/rte_mis_lottery/src/Batch/RandomizeStudent.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
Labels: Sprint 8

#344 RTEMIS-180: API creation for lottery
  .gitignore
  composer.json
  config/install/rest.resource.lottery_data_resource.yml
  config/install/simple_oauth.settings.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_lottery/asset/format.json
  modules/rte_mis_lottery/rte_mis_lottery.info.yml
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Plugin/rest/resource/LotteryDataResource.php
  rte_mis.info.yml
Labels: Sprint 8

#348 RTEMIS-183: Defined the schema for the School seat status table.
  modules/rte_mis_school/rte_mis_school.module
  rte_mis.install
Labels: Sprint 8

#346 RTEMIS-172: Modified the logic for different dashboards.
  modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php
Labels: Sprint 8

#350 RTEMIS-174: Theming updates for the font of school pdf.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 8

#351 RTEMIS-170: Added the landing page url to banner text.
  modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
Labels: Sprint 8

#347 RTEMIS-138: Node add twig patch.
  composer.json
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/user-login-page.scss
  patches/rtemis-node-custom-page.patch
Labels: Sprint 8

#353 RTEMIS-170: Header and footer logo theming.
  modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
  modules/rte_mis_gin/scss/navigation/_footer.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Sprint 8

#349 RTEMIS-183: Defined the schema for the School seat status table.
  composer.json
  config/install/filelog.settings.yml
  modules/rte_mis_lottery/config/install/rte_mis_lottery.settings.yml
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/src/Plugin/rest/resource/LotteryDataResource.php
  oauth_keys/.gitkeep
  rte_mis.info.yml
  rte_mis.install
Labels: Sprint 8

#356 RTEMIS-181: Added logic for lottery process.
  composer.json
  config/install/filelog.settings.yml
  modules/rte_mis_lottery/drush.services.yml
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/rte_mis_lottery.module
  modules/rte_mis_lottery/rte_mis_lottery.permissions.yml
  modules/rte_mis_lottery/rte_mis_lottery.routing.yml
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php
  modules/rte_mis_lottery/src/Commands/LotteryCommands.php
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Plugin/rest/resource/LotteryDataResource.php
  modules/rte_mis_lottery/src/Services/ClearTableManager.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Labels: Sprint 8

#359 RTEMIS-170: News popup fixes on mobil screen.
  config/install/colorbox.settings.yml
Labels: Sprint 8

#343 Dev to Main Merge
  .gitignore
  composer.json
  composer.lock
  grumphp.yml
  modules/rte_mis_gin/templates/page--front.html.twig
  modules/rte_mis_home/templates/statistics-block.html.twig
  modules/rte_mis_home/templates/two-column-block.html.twig
  scripts/composer/ScriptHandler.php
Labels: DO NOT MERGE

#358 RTEMIS-180: Lottery API Controller & hook_workflow.
  composer.json
  config/install/rest.resource.lottery_data_resource.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_lottery/rte_mis_lottery.info.yml
  modules/rte_mis_lottery/rte_mis_lottery.permissions.yml
  modules/rte_mis_lottery/rte_mis_lottery.routing.yml
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Plugin/rest/resource/LotteryDataResource.php
  modules/rte_mis_state/rte_mis_state.module
  rte_mis.info.yml
Labels: Sprint 8

#360 RTEMIS-138: Login page mobil and tab theming fixes.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/user-login-page.scss
Labels: Sprint 8

#362 RTEMIS-172: Block admin dashboard theming.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/homepage.scss
Labels: Sprint 8

#364 RTEMIS-184: Added Lottery results view.
  composer.json
  composer.lock
  config/install/user.role.state_admin.yml
  config/install/views.view.lottery_results.yml
  modules/rte_mis_lottery/config/install/rte_mis_lottery.settings.yml
  modules/rte_mis_lottery/config/install/view_custom_table.tables.yml
  modules/rte_mis_lottery/rte_mis_lottery.info.yml
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/rte_mis_lottery.links.menu.yml
  modules/rte_mis_lottery/rte_mis_lottery.module
  modules/rte_mis_lottery/rte_mis_lottery.routing.yml
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Access/StudentSmsAccessCheck.php
  modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php
  modules/rte_mis_lottery/src/Batch/SendSmsBatch.php
  modules/rte_mis_lottery/src/Commands/LotteryCommands.php
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Form/LotteryConfigForm.php
  modules/rte_mis_lottery/src/Form/SendSmsConfirmForm.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/LotteryDataDevelGenerates.php
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Labels: Sprint 9

#365 RTEMIS-0: Update the module name.
  modules/rte_mis_home/rte_mis_home.info.yml
Labels: Sprint 9

#366 RTEMIS-184: Added menu, drush command and fixed issues.
  config/install/menu_export.export_data.yml
  config/install/views.view.lottery_results.yml
  modules/rte_mis_lottery/drush.services.yml
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Commands/LotteryCommands.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  modules/rte_mis_student/rte_mis_student.module
Labels: Sprint 9

#370 RTEMIS-179: Lottery form table theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 9

#371 RTEMIS-184: Added script for processing lottery.
  scripts/lottery/process_lottery_data.sh
Labels: Sprint 9

#367 RTEMIS-172: Added scroll effect in table on mobil screen.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 9

#372 RTEMIS-184: Added lottery_id in seat_status table.
  modules/rte_mis_lottery/rte_mis_lottery.install
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  scripts/lottery/process_lottery_data.sh
Labels: Sprint 9

#374 RTEMIS-184: Fixed the issues.
  config/install/form_mode_control.settings.yml
  modules/rte_mis_allocation/rte_mis_allocation.info.yml
  modules/rte_mis_allocation/rte_mis_allocation.module
  modules/rte_mis_allocation/src/Plugin/QueueWorker/StudentAllocationDataQueue.php
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_lottery/rte_mis_lottery.info.yml
  modules/rte_mis_lottery/src/Commands/LotteryCommands.php
  modules/rte_mis_lottery/src/Controller/LotteryController.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
  modules/rte_mis_lottery/src/Plugin/QueueWorker/StudentDataQueue.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
  modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.default.yml
  modules/rte_mis_school/config/install/core.entity_form_display.mini_node.school_details.school_detail_edit.yml
  modules/rte_mis_student/config/optional/core.entity_form_display.mini_node.school_details.default.yml
  modules/rte_mis_student/config/optional/core.entity_form_display.mini_node.school_details.school_detail_edit.yml
  modules/rte_mis_student/config/optional/core.entity_form_display.paragraph.allotted_students_details.default.yml
  modules/rte_mis_student/config/optional/core.entity_view_display.mini_node.school_details.default.yml
  modules/rte_mis_student/config/optional/core.entity_view_display.mini_node.school_details.pdf.yml
  modules/rte_mis_student/config/optional/core.entity_view_display.paragraph.allotted_students_details.default.yml
  modules/rte_mis_student/config/optional/field.field.mini_node.school_details.field_allotted_students.yml
  modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_entry_class.yml
  modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_medium.yml
  modules/rte_mis_student/config/optional/field.field.paragraph.allotted_students_details.field_student_id.yml
  modules/rte_mis_student/config/optional/field.storage.mini_node.field_allotted_students.yml
  modules/rte_mis_student/config/optional/field.storage.paragraph.field_student_id.yml
  modules/rte_mis_student/config/optional/paragraphs.paragraphs_type.allotted_students_details.yml
  scripts/lottery/process_lottery_data.sh
Labels: Sprint 9

#375 RTEMIS-184: Optimized the randomize process.
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Batch/PrepareLotteryData.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Services/RteLotteryHelper.php
Labels: Sprint 9

#377 RTEMIS-138: Homepage theming issues.
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/scss/layout/homepage.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Sprint 9

#376 RTEMIS-187: Admission Status Page for Schools.
  config/install/views.view.allotted_students_details.yml
  modules/rte_mis_allocation/rte_mis_allocation.module
Labels: Sprint 9

#382 RTEMIS-189: Added workflow in allocation mini_node.
  composer.json
  composer.lock
  config/install/form_mode_control.settings.yml
  config/install/user.role.anonymous.yml
  config/install/user.role.authenticated.yml
  config/install/user.role.block_admin.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.school_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_allocation/config/install/core.entity_form_display.mini_node.allocation.default.yml
  modules/rte_mis_allocation/config/install/core.entity_form_display.workflow_transition.student_admission_workflow.default.yml
  modules/rte_mis_allocation/config/install/core.entity_view_display.mini_node.allocation.default.yml
  modules/rte_mis_allocation/config/install/core.entity_view_display.workflow_transition.student_admission_workflow.default.yml
  modules/rte_mis_allocation/config/install/field.field.mini_node.allocation.field_student_allocation_status.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_alternative_contact_number.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_current_contact_number.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_dropout_reason.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_is_migrating.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_location.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_other_school_name.yml
  modules/rte_mis_allocation/config/install/field.field.workflow_transition.student_admission_workflow.field_school.yml
  modules/rte_mis_allocation/config/install/field.storage.mini_node.field_student_allocation_status.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_alternative_contact_number.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_current_contact_number.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_dropout_reason.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_is_migrating.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_location.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_other_school_name.yml
  modules/rte_mis_allocation/config/install/field.storage.workflow_transition.field_school.yml
  modules/rte_mis_allocation/config/install/rte_mis_allocation.settings.yml
  modules/rte_mis_allocation/config/install/workflow.state.student_admission_workflow_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.state.student_admission_workflow_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.state.student_admission_workflow_creation.yml
  modules/rte_mis_allocation/config/install/workflow.state.student_admission_workflow_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.state.student_admission_workflow_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_admitted_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_admitted_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_admitted_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_admitted_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_allotted_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_allotted_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_allotted_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_allotted_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_creation_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_creation_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_creation_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_creation_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_dropout_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_dropout_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_dropout_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_dropout_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_not_admitted_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_not_admitted_allotted.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_not_admitted_dropout.yml
  modules/rte_mis_allocation/config/install/workflow.transition.student_admission_workflow_not_admitted_not_admitted.yml
  modules/rte_mis_allocation/config/install/workflow.workflow.student_admission_workflow.yml
  modules/rte_mis_allocation/rte_mis_allocation.info.yml
  modules/rte_mis_allocation/rte_mis_allocation.module
  modules/rte_mis_allocation/src/Plugin/QueueWorker/StudentAllocationDataQueue.php
Labels: Sprint 9

#380 RTEMIS-187: Added exposed filter.
  config/install/user.role.school_admin.yml
  config/install/views.view.allotted_students_details.yml
  modules/rte_mis_allocation/rte_mis_allocation.module
  modules/rte_mis_allocation/rte_mis_allocation.services.yml
  modules/rte_mis_allocation/src/Access/AllocationDetailEditAccessCheck.php
  modules/rte_mis_allocation/src/Routing/RouteSubscriber.php
Labels: Sprint 9

#378 RTEMIS-138: Fixed the spinbox on input field issue.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 9

#384 RTEMIS-188: Student Admission Report Page for States.
  config/install/menu_export.export_data.yml
  config/install/user.role.block_admin.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_allocation/rte_mis_allocation.links.menu.yml
  modules/rte_mis_allocation/rte_mis_allocation.permissions.yml
  modules/rte_mis_allocation/rte_mis_allocation.routing.yml
  modules/rte_mis_allocation/src/Access/AllocationDetailEditAccessCheck.php
  modules/rte_mis_allocation/src/Controller/StudentAdmissionReportController.php
  modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 9

#388 RTEMIS-190: Student allocation section theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 9

#390 RTEMIS-199: Added additional fields in the student performance.
  modules/rte_mis_allocation/rte_mis_allocation.module
  modules/rte_mis_student_tracking/config/install/core.entity_form_display.mini_node.student_performance.default.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.allocation_details.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.default.yml
  modules/rte_mis_student_tracking/config/install/core.entity_view_display.mini_node.student_performance.pdf.yml
  modules/rte_mis_student_tracking/config/install/eck.eck_type.mini_node.student_performance.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_academic_session.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_caste.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_current_class.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_date_of_birth.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_entry_class_for_allocation.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_entry_year.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_final_grade.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_final_rank.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_gender.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_medium.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_mobile_number.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_parent_name.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_promoted_class.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_religion.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_residential_address.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_school.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_student.yml
  modules/rte_mis_student_tracking/config/install/field.field.mini_node.student_performance.field_total_attendance.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_academic_session.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_current_class.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_entry_year.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_final_grade.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_final_rank.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_parent_name.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_promoted_class.yml
  modules/rte_mis_student_tracking/config/install/field.storage.mini_node.field_total_attendance.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.info.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.module
  rte_mis.info.yml
Labels: Sprint 10

#391 RTEMIS-200: Added configuration form for rte_mis_student_tracking.
  config/install/user.role.state_admin.yml
  modules/rte_mis_student_tracking/config/install/rte_mis_student_tracking.settings.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.info.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.permissions.yml
  modules/rte_mis_student_tracking/rte_mis_student_tracking.routing.yml
  modules/rte_mis_student_tracking/src/Form/RteMisStudentTrackingConfigForm.php
Labels: Sprint 10
