Repository Indus-Action-Initiatives/rte-mis, pull requests merged in 2024-05, with the labels that each got.

#140 RTEMIS-123: List of eligible schools field.
  composer.json
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_class.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_date_of_birth.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_school_preference.yml
  modules/rte_mis_student/config/install/field.storage.mini_node.field_class.yml
  modules/rte_mis_student/config/install/field.storage.mini_node.field_date_of_birth.yml
  modules/rte_mis_student/config/install/field.storage.mini_node.field_school_preference.yml
  modules/rte_mis_student/config/install/rte_mis_student.settings.yml
  modules/rte_mis_student/rte_mis_student.info.yml
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Sprint 6

#165 RTEMIS-138 : Using single file for login and reset forms.
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/templates/page--user-login.html.twig
  modules/rte_mis_gin/templates/page--user-password.html.twig
  modules/rte_mis_gin/templates/page--user-register.html.twig
Labels: Sprint 6

#166 RTEMIS-130: Position and color changes in the form.
  modules/rte_mis_gin/scss/base/_color.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Sprint 6

#167 RTEMIS-30: Pdf theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 6

#168 RTEMIS-121: Updated the static field.
  composer.json
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_has_siblings.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_hiv.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_orphan.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_single_girl_child.yml
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Sprint 6

#170 RTEMIS-138: Theming of submenu.
  modules/rte_mis_core/templates/block--site-pre-menu-text-section-block.html.twig
  modules/rte_mis_gin/js/register-form.js
  modules/rte_mis_gin/js/script.js
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Sprint 6

#171 RTEMIS-138: Themed the hero banner.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
  modules/rte_mis_gin/templates/page--custom.html.twig
Labels: Sprint 6

#177 RTEMIS-133: Implemented Student Application Status Feature.
  config/install/views.view.school_registration.yml
  config/install/views.view.student_registration.yml
  modules/rte_mis_student/config/install/views.view.student_applications.yml
  modules/rte_mis_student/rte_mis_student.routing.yml
  modules/rte_mis_student/src/Controller/StudentApplicationController.php
  modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Labels: Sprint 6

#178 RTEMIS-130: Changed the breadcrumb color.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Sprint 6

#180 RTEMIS-123: Updated school eligible feature.
  composer.json
  config/install/views.view.student_registration.yml
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/core.entity_form_display.paragraph.school_preference.default.yml
  modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/core.entity_view_display.paragraph.school_preference.default.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_school_preferences.yml
  modules/rte_mis_student/config/install/field.field.paragraph.school_preference.field_medium.yml
  modules/rte_mis_student/config/install/field.field.paragraph.school_preference.field_school_id.yml
  modules/rte_mis_student/config/install/field.storage.mini_node.field_school_preferences.yml
  modules/rte_mis_student/config/install/field.storage.paragraph.field_school_id.yml
  modules/rte_mis_student/config/install/paragraphs.paragraphs_type.school_preference.yml
  modules/rte_mis_student/rte_mis_student.info.yml
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
  modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Labels: Sprint 6

#182 RTEMIS-130: Email validation message in printing once now.
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Sprint 6

#184 RTEMIS-134: School application print form theming.
  modules/rte_mis_gin/scss/layout/_student-details.scss
  modules/rte_mis_gin/scss/main.scss
Labels: Sprint 6

#183 RTEMIS-139: Fixed the breadcrumb position issue and modified menu icons.
  config/install/block.block.gin_mainmenu.yml
  config/install/block.block.gin_sitelogosection.yml
  config/install/block.block.gin_sitepremenutextheader.yml
  config/install/block.block.gin_useraccountmenu.yml
  config/install/easy_breadcrumb.settings.yml
  config/install/gin_toolbar_custom_menu.settings.yml
Labels: Sprint 6

#185 RTEMIS-30: Modification in pdf design.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 6

#188 RTEMIS-130: Modified the labels for the email verification field.
  modules/rte_mis_mail/rte_mis_mail.module
Labels: Sprint 6

#191 RTEMIS-138: Global theming updates for forms.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/_student-details.scss
Labels: Sprint 6

#189 RTEMIS-134: Added the label for the Location field.
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Sprint 6

#194 RTEMIS-137: Added the markup texts.
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Sprint 6

#196 RTEMIS-122: Implemented student edit for block admin.
  .lando.yml
  config/install/config_ignore.settings.yml
  config/install/field.field.user.user.field_phone_number.yml
  config/install/user.role.block_admin.yml
  config/install/views.view.student_registration.yml
  modules/rte_mis_school/config/install/core.entity_view_display.mini_node.school_details.default.yml
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/rte_mis_student.services.yml
  modules/rte_mis_student/src/Access/StudentDetailEditAccessCheck.php
  modules/rte_mis_student/src/Access/StudentRegisterAccessCheck.php
  modules/rte_mis_student/src/EventSubscriber/StudentLoginEventSubscriber.php
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
  modules/rte_mis_student/src/Form/StudentLoginForm.php
  modules/rte_mis_student/src/Routing/RouteSubscriber.php
  modules/rte_mis_student/src/Services/MobileOtpService.php
Labels: Sprint 6

#197 RTEMIS-126: Removed the empty sibling details from entity view.
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Sprint 6

#199 RTEMIS-133: Rename registration number to application number.
  modules/rte_mis_student/src/Form/StudentApplicationStatusForm.php
Labels: Sprint 6

#200 RTEMIS-134: Student form theming.
  modules/rte_mis_gin/scss/base/_color.scss
  modules/rte_mis_gin/scss/layout/_student-details.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Sprint 6

#198 RTEMIS-131: Modified the Student Application Print.
  modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Sprint 6

#201 RTEMIS-131: Added the Application Status field in the Student Pdf.
  modules/rte_mis_student/config/install/core.entity_view_display.mini_node.student_details.pdf.yml
  modules/rte_mis_student/src/Access/StudentPdfDownloadAccessCheck.php
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Sprint 6

#176 RTEMIS-0: Updated the menu links and check issue.
  config/install/menu_export.export_data.yml
  modules/rte_mis_gin/rte_mis_gin.module
Labels: Sprint 6

#204 RTEMIS-00: Updated the menus.
  config/install/menu_export.export_data.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  config/install/views.view.school_registration.yml
  config/install/views.view.student_registration.yml
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Access/StudentDetailViewAccessCheck.php
Labels: Sprint 6

#205 RTEMIS-131: Fixed the Rural/Urban issue.
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Sprint 6

#207 RTEMIS-134: Student details form theming.
  modules/rte_mis_gin/scss/layout/_student-details.scss
Labels: Sprint 6

#208 RTEMIS-134: Student form theming updates.
  modules/rte_mis_gin/scss/layout/_student-details.scss
Labels: Sprint 6

#211 RTEMIS-152: Modified the Captcha Settings.
  config/install/captcha.settings.yml
Labels: Demo-Feedback

#214 RTEMIS-156: Resolved BE feedbacks of UDISE.
  config/install/user.role.state_admin.yml
  config/install/views.view.school.yml
  modules/rte_mis_core/js/general.js
  modules/rte_mis_core/js/restrict_number_input.js
  modules/rte_mis_core/rte_mis_core.libraries.yml
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_core/src/Form/OverrideTermForm.php
  modules/rte_mis_school/config/install/core.entity_form_display.taxonomy_term.school.default.yml
  modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_school_recognition_number.yml
  modules/rte_mis_school/config/install/language.content_settings.taxonomy_term.school.yml
  modules/rte_mis_school/config/install/workflow.workflow.school_workflow.yml
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_school/src/Form/BulkUploadSchoolsForm.php
  modules/rte_mis_state/rte_mis_state.module
Labels: Demo-Feedback

#216 RTEMIS-155: Student registration form theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Demo-Feedback

#217 RTEMIS-155: School registration view node theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Demo-Feedback

#218 RTEMIS-153: Moved the lang dropdown to breadcrumb region.
  composer.json
  modules/rte_mis_multilingual/config/optional/block.block.gin_languagedropdownswitcher.yml
  modules/rte_mis_multilingual/rte_mis_multilingual.info.yml
Labels: Demo-Feedback

#221 RTEMIS-155: Language dropdown theming on submenu.
  modules/rte_mis_gin/scss/base/_breakpoints.scss
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/base/_reset.scss
  modules/rte_mis_gin/scss/layout/user-login-page.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Demo-Feedback

#220 RTEMIS-138: Global font size 16px.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/_student-details.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Demo-Feedback

#222 RTEMIS-155: Content add node theming.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Demo-Feedback

#225 RTEMIS-159: Resolved multiple issues(academic, language, registration section).
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Demo-Feedback

#227 RTEMIS-138: School pending view theming.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
Labels: Demo-Feedback

#228 RTEMIS-161: Resolved school mapping feedback.
  config/install/menu_export.export_data.yml
  config/install/user.role.district_admin.yml
  modules/rte_mis_core/js/disable_cshs_select.js
  modules/rte_mis_core/js/general.js
  modules/rte_mis_core/rte_mis_core.libraries.yml
  modules/rte_mis_school/src/Form/SchoolMappingForm.php
  modules/rte_mis_state/rte_mis_state.module
Labels: Demo-Feedback

#224 RTEMIS-154: Fixed the Admin Section BE Issues.
  config/install/administerusersbyrole.settings.yml
  config/install/menu_export.export_data.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_state/rte_mis_state.services.yml
  modules/rte_mis_state/src/Access/UserEditAccessCheck.php
  modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php
  modules/rte_mis_state/src/Routing/RouteSubscriber.php
  rte_mis.install
Labels: Demo-Feedback

#229 RTEMIS-155: Layout fixes on different viewports.
  modules/rte_mis_gin/js/script.js
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/user-login-page.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Demo-Feedback

#230 RTEMIS-152: Fixed the breadcrumb issue.
  composer.json
  config/install/easy_breadcrumb.settings.yml
  config/install/menu_export.export_data.yml
  config/install/pathauto.pattern.academic_sessions_alias.yml
  config/install/pathauto.pattern.location_alias.yml
  config/install/pathauto.pattern.school_alias.yml
  config/install/pathauto.pattern.school_mini_node_alias.yml
  config/install/pathauto.pattern.student_details_alias.yml
  config/install/pathauto.settings.yml
  config/install/subpathauto.settings.yml
  modules/rte_mis_mail/rte_mis_mail.module
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
  patches/breadcrumb_edit_fix.patch
  rte_mis.info.yml
Labels: Demo-Feedback

#231 RTEMIS-152: Modified breadcrumb.
  config/install/easy_breadcrumb.settings.yml
Labels: Demo-Feedback

#233 RTEMIS-155: Student form theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/_student-details.scss
Labels: Demo-Feedback

#236 RTEMIS-001: Resolved multiple feedback.
  config/install/menu_export.export_data.yml
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_core/src/Plugin/Menu/AlterTaxonomyActionTask.php
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
Labels: Demo-Feedback

#238 RTEMIS-155: Student edit form theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Demo-Feedback

#240 RTEMIS-138: Under construction page theming.
  modules/rte_mis_core/src/Controller/UnderConstruction.php
  modules/rte_mis_gin/scss/layout/under-construction.scss
Labels: Demo-Feedback

#243 RTEMIS-162: Location Overiview Panel.
  modules/rte_mis_student/src/CustomVocabularyListBuilder.php
  modules/rte_mis_student/src/Routing/RouteSubscriber.php
Labels: Demo-Feedback

#242 RTEMIS-154: Fixed the People Page.
  config/install/easy_breadcrumb.settings.yml
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php
Labels: Demo-Feedback

#245 RTEMIS-162: Location Overview Panel.
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/src/CustomVocabularyListBuilder.php
Labels: Demo-Feedback

#249 RTEMIS-138: Forms alignment theming.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
Labels: Demo-Feedback

#253 RTEMIS-132: Added patch for entity_print.
  composer.json
  config/install/entity_print.settings.yml
Labels: Demo-Feedback

#251 RTEMIS-138: Academic session edit form theming.
  modules/rte_mis_gin/scss/base/_global.scss
Labels: Demo-Feedback

#255 RTEMIS-138: Used edit form theming updates.
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Demo-Feedback

#256 RTEMIS-138: Madhu feedback changes.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/layout/user-login-page.scss
  modules/rte_mis_gin/scss/layout/user-register-page.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
  modules/rte_mis_school/rte_mis_school.module
Labels: Demo-Feedback

#259 RTEMIS-132: Reverted the style changes.
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/scss/layout/school-details-style.scss
  modules/rte_mis_gin/scss/layout/student-details-style.scss
  modules/rte_mis_school/src/EventSubscriber/SchoolEntityPrintCssAlterSubscriber.php
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
  modules/rte_mis_student/rte_mis_student.services.yml
  modules/rte_mis_student/src/EventSubscriber/StudentEntityPrintCssAlterSubscriber.php
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Demo-Feedback

#193 RTE-MIS-Functional-Doc-Modifications-and-creation
  docs/appadmin.html
  docs/index.html
  docs/school.html
  docs/state.html
  docs/student.html
Labels: documentation

#263 RTEMIS-132: Updated the icon for pdf.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Demo-Feedback

#264 Revert - RTEMIS-132: Updated the icon for pdf.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Demo-Feedback

#261 RTEMIS-138: Footer mail text property modification.
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Demo-Feedback

#262 RTEMIS-169: Feedback issues resolved.
  composer.json
  config/install/block.block.gin_languagedropdownswitcher.yml
  config/install/block.block.gin_sitelogosection.yml
  config/install/block.block.gin_sitelogosection_2.yml
  config/install/easy_breadcrumb.settings.yml
  config/install/mail_login.settings.yml
  config/install/menu_export.export_data.yml
  modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
  modules/rte_mis_mail/src/Element/RteMobileNumber.php
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_state/src/Plugin/Menu/AlterPeopleActionTask.php
  modules/rte_mis_student/config/install/core.entity_form_display.mini_node.student_details.default.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_birth_proof.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_has_siblings.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_orphan.yml
  modules/rte_mis_student/config/install/field.field.mini_node.student_details.field_single_girl_child.yml
  modules/rte_mis_student/rte_mis_student.routing.yml
  modules/rte_mis_student/src/Form/OverrideMiniNodeForm.php
  rte_mis.info.yml
Labels: Demo-Feedback

#266 Rtemis 138 : Updated by madhu on student page and logo updates.
  modules/rte_mis_core/asset/img/Emblem_of_India.svg
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Demo-Feedback

#265 RTEMIS-169: Additional feedbacks.
  config/install/block.block.gin_sitelogosection.yml
  config/install/block.block.gin_sitelogosection_2.yml
  modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
  modules/rte_mis_state/rte_mis_state.module
Labels: Demo-Feedback
