Repository Indus-Action-Initiatives/rte-mis, pull requests merged in 2024-06, with the labels that each got.

#271 RTEMIS-166: Modified the pdf template for school.
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Demo-Feedback

#268 RTEMIS-05: Fixed multiple issues.
  composer.json
  config/install/administerusersbyrole.settings.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_core/config/install/core.entity_form_display.taxonomy_term.location.default.yml
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_core/src/Form/OverrideTermForm.php
  modules/rte_mis_core/src/Helper/RteCoreHelper.php
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_state/rte_mis_state.module
  rte_mis.install
Labels: Demo-Feedback

#274 RTEMIS-170: Home Page for RTE
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/scss/layout/homepage.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
  modules/rte_mis_gin/templates/page--front.html.twig
  modules/rte_mis_home/assets/statistics/district.svg
  modules/rte_mis_home/assets/statistics/reimbursement.svg
  modules/rte_mis_home/assets/statistics/school.svg
  modules/rte_mis_home/assets/statistics/seats.svg
  modules/rte_mis_home/assets/statistics/student.svg
  modules/rte_mis_home/src/Plugin/Block/StatisticsBlock.php
  modules/rte_mis_home/templates/statistics-block.html.twig
Labels: Sprint 7

#270 RTEMIS-138: School register form input width.
  modules/rte_mis_gin/scss/layout/user-register-page.scss
Labels: Demo-Feedback

#275 RTEMIS-165: Added validation for aadhar card.
  modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js
  modules/rte_mis_student/rte_mis_student.module
Labels: Sprint 7

#277 RTEMIS-05: Fixed the Adminsiter User By Role module issue for profiles.
  composer.json
  config/install/user.role.state_admin.yml
  patches/administerusersbyrole.patch
  rte_mis.install
Labels: Sprint 7

#273 RTEMIS-164: Modified the success message on term create and update.
  modules/rte_mis_core/src/Form/OverrideTermForm.php
Labels: Sprint 7

#279 RTEMIS-167: Fixed the tab issue.
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_gin/rte_mis_gin.module
Labels: Sprint 7

#281 RTEMIS-170: Testimonail slider theming.
  composer.json
  modules/rte_mis_gin/js/testimonial.js
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/templates/block--testimonials.html.twig
  modules/rte_mis_home/config/install/core.entity_form_display.media.news_update.default.yml
  modules/rte_mis_home/config/install/field.field.media.video.field_video_thumbnail.yml
  modules/rte_mis_home/config/install/views.view.news_updates.yml
  modules/rte_mis_home/config/install/views.view.videos.yml
  modules/rte_mis_home/rte_mis_home.info.yml
  rte_mis.info.yml
Labels: Sprint 7

#278 RTEMIS-05: Modified the school pdf to define dynamic entry class data.
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
Labels: Sprint 7

#282 RTEMIS-170: News component theming and modification in testimonials component.
  composer.json
  config/install/block.block.gin_twocolumnblock.yml
  config/install/block.block.gin_views_block__authorities.yml
  config/install/block.block.gin_views_block__news_updates.yml
  config/install/block.block.gin_views_block__testimonials.yml
  config/install/block_class.settings.yml
  config/install/config_ignore.settings.yml
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/block/two-column-block.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/templates/block--authorities.html.twig
  modules/rte_mis_gin/templates/block--testimonials.html.twig
  modules/rte_mis_gin/templates/views-view-unformatted--custom.html.twig
  modules/rte_mis_home/assets/two_column_block/two_column_image.jpeg
  modules/rte_mis_home/config/install/core.entity_form_display.media.video.default.yml
  modules/rte_mis_home/config/install/core.entity_view_display.media.video.default.yml
  modules/rte_mis_home/config/install/field.field.media.video.field_media_video_file.yml
  modules/rte_mis_home/config/install/field.field.media.video.field_video_link.yml
  modules/rte_mis_home/config/install/field.field.media.video.field_video_type.yml
  modules/rte_mis_home/config/install/field.storage.media.field_video_type.yml
  modules/rte_mis_home/config/schema/rte_mis_home.schema.yml
  modules/rte_mis_home/rte_mis_home.info.yml
  modules/rte_mis_home/rte_mis_home.module
  modules/rte_mis_home/src/Plugin/Block/TwoColumnBlock.php
  modules/rte_mis_home/templates/two-column-block.html.twig
  rte_mis.info.yml
Labels: Sprint 7

#284 RTEMIS-170: Eligbility criteria theming.
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/block/eligibility-criteria.scss
  modules/rte_mis_gin/scss/block/two-column-block.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/scss/components/video-block.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
  modules/rte_mis_home/src/Plugin/Block/EligibilityCriteriaBlock.php
  modules/rte_mis_home/src/Plugin/Block/StatisticsBlock.php
  modules/rte_mis_home/templates/eligibility-criteria.html.twig
  modules/rte_mis_home/templates/two-column-block.html.twig
Labels: Sprint 7

#286 RTEMIS-168: Fixed the regression issue for School Udise Code.
  composer.json
  modules/rte_mis_school/rte_mis_school.module
Labels: Sprint 7

#290 RTEMIS-175: About us page theming.
  composer.json
  config/install/block.block.gin_content.yml
  config/install/block.block.gin_local_actions.yml
  config/install/block_class.settings.yml
  config/install/core.base_field_override.node.page.promote.yml
  config/install/core.entity_form_display.node.page.default.yml
  config/install/core.entity_view_display.node.page.default.yml
  config/install/core.entity_view_display.node.page.teaser.yml
  config/install/editor.editor.full_html.yml
  config/install/field.field.node.page.body.yml
  config/install/field.storage.node.body.yml
  config/install/filter.format.full_html.yml
  config/install/language.content_settings.node.page.yml
  config/install/node.type.page.yml
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/video-block.scss
  modules/rte_mis_gin/scss/layout/about-us.scss
  modules/rte_mis_gin/templates/node--page.html.twig
  modules/rte_mis_gin/templates/page--custom.html.twig
  modules/rte_mis_home/rte_mis_home.module
  rte_mis.info.yml
Labels: Sprint 7

#292 RTEMIS-138: Theming updates in about us page and menu.
  modules/rte_mis_gin/js/register-form.js
  modules/rte_mis_gin/js/script.js
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/component-authority.scss
  modules/rte_mis_gin/scss/layout/about-us.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Sprint 7

#293 RTEMIS-138: Static pages theming.
  modules/rte_mis_gin/scss/layout/about-us.scss
  modules/rte_mis_gin/templates/node--page.html.twig
Labels: Sprint 7

#283 RTEMIS-174: Made content translatable.
  composer.json
  config/install/block.block.gin_languagedropdownswitcher.yml
  config/install/views.view.academic_sessions_list.yml
  config/install/views.view.school_registration.yml
  modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_education_details.yml
  modules/rte_mis_school/config/install/field.field.mini_node.school_details.field_entry_class.yml
  modules/rte_mis_school/rte_mis_school.links.action.yml
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_school/src/Form/SchoolMappingForm.php
  modules/rte_mis_school/src/Plugin/Menu/SchoolRegistrationLocalTask.php
  modules/rte_mis_state/config/install/core.entity_view_display.paragraph.timeline.default.yml
  modules/rte_mis_state/rte_mis_state.links.action.yml
  modules/rte_mis_state/rte_mis_state.module
  modules/rte_mis_student/config/install/views.view.student_applications.yml
Labels: Sprint 7

#295 RTEMIS-138: Text alignment chnages.
  modules/rte_mis_gin/js/script.js
  modules/rte_mis_gin/js/testimonial.js
  modules/rte_mis_gin/scss/layout/about-us.scss
  modules/rte_mis_gin/scss/navigation/_header.scss
Labels: Sprint 7

#206 RTEMIS-127: Created a custom module for demo content.
  modules/rte_mis_core/src/Batch/LocationTermBatch.php
  modules/rte_mis_demo_content/asset/location_demo.xlsx
  modules/rte_mis_demo_content/asset/upload-bulk-school-udise.xlsx
  modules/rte_mis_demo_content/rte_mis_demo_content.info.yml
  modules/rte_mis_demo_content/rte_mis_demo_content.install
  modules/rte_mis_demo_content/rte_mis_demo_content.module
  modules/rte_mis_demo_content/rte_mis_demo_content.services.yml
  modules/rte_mis_demo_content/src/TestData.php
  modules/rte_mis_school/src/Batch/SchoolBatch.php
Labels: Sprint 7

#297 RTEMIS-170: Popup theming and header & background image.
  composer.json
  config/install/colorbox.settings.yml
  modules/rte_mis_gin/js/testimonial.js
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
  modules/rte_mis_gin/templates/views-view-unformatted--custom.html.twig
  modules/rte_mis_home/config/install/core.entity_form_display.media.news_update.default.yml
  modules/rte_mis_home/config/install/core.entity_view_display.media.news_update.default.yml
  modules/rte_mis_home/config/install/field.field.media.news_update.field_news_thumbnail.yml
  modules/rte_mis_home/config/install/field.storage.media.field_news_thumbnail.yml
  modules/rte_mis_home/config/install/views.view.news_updates.yml
  modules/rte_mis_home/config/install/views.view.notifications.yml
  modules/rte_mis_home/rte_mis_home.info.yml
  rte_mis.info.yml
Labels: Sprint 7

#303 RTEMIS-165: Modified the error message for student aadhar validation.
  modules/rte_mis_student/js/rte_mis_student_aadhar_validation.js
Labels: Sprint 7

#301 RTEMIS-177: Removed local tasks for all user except app_admin and moved school registration to menu.
  config/install/block.block.gin_primary_local_tasks.yml
  config/install/menu_export.export_data.yml
  modules/rte_mis_school/rte_mis_school.links.menu.yml
  modules/rte_mis_school/rte_mis_school.links.task.yml
  modules/rte_mis_school/src/Plugin/Derivative/SchoolRegistrationMenuLink.php
  modules/rte_mis_school/src/Plugin/Menu/SchoolRegistrationLocalTask.php
  modules/rte_mis_school/src/Plugin/Menu/SchoolRegistrationMenuLink.php
  modules/rte_mis_state/rte_mis_state.module
Labels: Sprint 7

#307 RTEMIS-174: Updated font settings for pdf.
  modules/rte_mis_school/rte_mis_school.module
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
  modules/rte_mis_student/rte_mis_student.module
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Sprint 7

#308 RTEMIS-0: Update the page title for school admin.
  modules/rte_mis_core/rte_mis_core.module
Labels: Sprint 7

#302 RTEMIS-164: Modified the title, success message and overview form.
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_core/src/Form/OverrideTermDeleteForm.php
  modules/rte_mis_school/templates/eck-entity--mini-node--school-details--pdf.html.twig
  modules/rte_mis_student/src/CustomVocabularyListBuilder.php
Labels: Sprint 7

#309 RTEMIS-176: Dashboard should be the default page for user.
  composer.json
  config/install/redirect_after_login.settings.yml
  rte_mis.info.yml
Labels: Sprint 7

#305 RTEMIS-178: Created Sitemap for ths site.
  composer.json
  config/install/menu_export.export_data.yml
  config/install/sitemap.settings.yml
  config/install/tour.tour.sitemap.yml
  config/install/user.role.anonymous.yml
  modules/rte_mis_core/src/Menu/OverrideSiteMap.php
  modules/rte_mis_core/src/RteMisCoreServiceProvider.php
  modules/rte_mis_gin/rte_mis_gin.libraries.yml
  modules/rte_mis_gin/rte_mis_gin.module
  modules/rte_mis_gin/scss/layout/sitemap.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
  rte_mis.info.yml
Labels: Sprint 7

#310 RTEMIS-178: Sitemap node school menu display block.
  modules/rte_mis_gin/scss/layout/sitemap.scss
Labels: Sprint 7

#312 RTEMIS-0: Set timezone for timeline events.
  modules/rte_mis_core/src/Helper/RteCoreHelper.php
Labels: Sprint 7

#314 RTEMIS-170: Theming of registration closed text.
  modules/rte_mis_gin/scss/block/eligibility-criteria.scss
  modules/rte_mis_home/templates/eligibility-criteria.html.twig
Labels: Sprint 7

#313 RTEMIS-178: Social links sitemap theming.
  modules/rte_mis_gin/scss/layout/sitemap.scss
Labels: Sprint 7

#311 RTEMIS-172: Created dashboard for different user roles.
  config/install/menu_export.export_data.yml
  config/install/redirect_after_login.settings.yml
  config/install/user.role.block_admin.yml
  config/install/user.role.district_admin.yml
  config/install/user.role.state_admin.yml
  modules/rte_mis_core/config/install/dashboards.dashboard.block_dashboard.yml
  modules/rte_mis_core/config/install/dashboards.dashboard.district_dashboard.yml
  modules/rte_mis_core/config/install/dashboards.dashboard.school_dashboard.yml
  modules/rte_mis_core/config/install/dashboards.dashboard.state_dashboard.yml
  modules/rte_mis_core/rte_mis_core.info.yml
  modules/rte_mis_core/rte_mis_core.module
  modules/rte_mis_core/src/Plugin/Block/RoleBasedDetailsBlock.php
  modules/rte_mis_core/src/Plugin/Block/TasksStatusBlock.php
  modules/rte_mis_core/templates/dynamic-dashboard-block.html.twig
  modules/rte_mis_core/templates/tasks-status-block.html.twig
  modules/rte_mis_gin/scss/block/tasks-status-block.scss
  modules/rte_mis_home/rte_mis_home.info.yml
  modules/rte_mis_school/rte_mis_school.module
Labels: Sprint 7

#315 RTEMIS-0: Added translation for menu and custom options.
  config/install/language.content_settings.menu_link_content.menu_link_content.yml
  config/install/language/hi/block.block.gin_sitelogosection.yml
  config/install/language/hi/block.block.gin_sitelogosection_2.yml
  config/install/language/hi/block.block.gin_sitepremenutextheader.yml
  modules/rte_mis_core/src/Batch/LocationTermBatch.php
  modules/rte_mis_school/config/install/language/hi/rte_mis_school.settings.yml
  modules/rte_mis_school/src/Batch/SchoolBatch.php
  modules/rte_mis_student/config/install/language/hi/rte_mis_student.settings.yml
  modules/rte_mis_student/config/install/rte_mis_student.settings.yml
Labels: Sprint 7

#317 RTEMIS-0: Locked the gin version in composer.
  composer.json
Labels: Sprint 7

#320 RTEMIS-11: Added schema for rte_mis_home_two_column_block.
  config/install/language/hi/block.block.gin_eligibilitycriteria.yml
  config/schema/rte_mis.schema.yml
  modules/rte_mis_gin/templates/page--front.html.twig
  modules/rte_mis_home/config/install/language/hi/eck.eck_type.mini_node.notifications.yml
  modules/rte_mis_home/config/install/language/hi/views.view.notifications.yml
  modules/rte_mis_home/config/install/views.view.notifications.yml
  modules/rte_mis_home/rte_mis_home.module
  modules/rte_mis_home/src/Plugin/Block/EligibilityCriteriaBlock.php
  modules/rte_mis_home/src/Plugin/Block/StatisticsBlock.php
  modules/rte_mis_home/templates/eligibility-criteria.html.twig
Labels: Sprint 7

#321 RTEMIS-172: Modified the dashboard.
  modules/rte_mis_core/src/Plugin/Block/TasksStatusBlock.php
Labels: Sprint 7

#322 RTEMIS-0: User View email fix and search icon removed.
  config/install/menu_export.export_data.yml
  config/install/views.view.user_basic_information.yml
  modules/rte_mis_demo_content/asset/upload-bulk-school-udise.xlsx
Labels: Sprint 7

#323 RTEMIS-138: Captalize the titles and testimonial popup image size.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_home/templates/eligibility-criteria.html.twig
Labels: Sprint 7

#325 RTEMIS-175: Static pages theming updates.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_gin/scss/components/component-testimonials.scss
  modules/rte_mis_gin/scss/layout/about-us.scss
Labels: Sprint 7

#339 RTEMIS-179: Randomize students for lottery.
  composer.json
  modules/rte_mis_lottery/rte_mis_lottery.info.yml
  modules/rte_mis_lottery/rte_mis_lottery.permissions.yml
  modules/rte_mis_lottery/rte_mis_lottery.routing.yml
  modules/rte_mis_lottery/rte_mis_lottery.services.yml
  modules/rte_mis_lottery/src/Access/LotteryAccessCheck.php
  modules/rte_mis_lottery/src/Batch/RandomizeStudent.php
  modules/rte_mis_lottery/src/Form/LotteryForm.php
  modules/rte_mis_lottery/src/Plugin/DevelGenerate/MiniNodeDevelGenerates.php
Labels: Sprint 8

#333 RTEMIS-170: Added front page link to the header and footer image.
  modules/rte_mis_core/src/Plugin/Block/SiteLogoSectionBlock.php
  modules/rte_mis_gin/scss/layout/about-us.scss
  modules/rte_mis_gin/scss/navigation/_footer.scss
Labels: Sprint 8

#340 RTEMIS-174: PDF theming and restructuring.
  modules/rte_mis_gin/scss/base/_global.scss
  modules/rte_mis_student/templates/eck-entity--mini-node--student-details--pdf.html.twig
Labels: Sprint 8

#334 RTEMIS-175: Fixed the static page breadcrumb issue.
  composer.json
  patches/gin_breadcrumb_edit_fix.patch
Labels: Sprint 8
